name: CI

on: [push, pull_request]

jobs:
  rustfmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check

  tests:
    name: Tests (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  tests-msrv:
    name: Tests (MSRV)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.81
      - run: cargo test

  build-no_std:
    name: Build no_std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv7m-none-eabi
      - run: cargo build --target thumbv7m-none-eabi

  build-benches:
    name: Build benches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo bench --no-run

  check-readme:
    name: Check readme
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-readme
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: just check-readme
